version: "3.3"

services:
  mysql:
    restart: always
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - /home/gabrielnp/git/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  server:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    restart: always
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - /home/gabrielnp/git:/var/www/html
